spring:
  application:
    name: pal-tracker

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/tracker_dev?useSSL=false
    username: root
    password: mysql
